<?php

//Automatically register any blocks generated by the npm run build command (build folder)

function create_blocks() {

    // $folder = dirname(__FILE__) . '/build';
    // $name_folder = array();
    // $files = scandir($folder);

    // foreach($files as $file) {
    //     if(is_dir($folder . '/' . $file)) {
    //         $name_folder[] = $file;
    //     }
    // }

    // foreach ($name_folder as $key => $value) {
    //     if($value == "." || $value == ".." || $value == "images") continue;
    //     register_block_type( dirname(__FILE__) . '/build' . '/' . $value );
    // }

	register_block_type( dirname(__FILE__) . '/build/ajax-get-block' );
	register_block_type( dirname(__FILE__) . '/build/ajax-get-block-php' );
    
   
}
add_action( 'init', 'create_blocks' );




